apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: default
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istio-distribution
    targetRevision: 1.22.0
    helm:
      values: |
        components:
          base:
            enabled: true
          pilot:
            enabled: true
            k8s:
              env:
                - name: ENABLE_AMBIENT_MODE
                  value: "true"
        meshConfig:
          defaultConfig:
            proxyMetadata:
              ISTIO_META_ENABLE_AMBIENT: "true"
        gateways:
          istio-ingressgateway:
            enabled: true
            type: LoadBalancer
          istio-egressgateway:
            enabled: true
            type: ClusterIP
  destination:
    server: '{{server}}'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
